name: Pull request checks
on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    
jobs:
  pull-request-checks:
    runs-on: [self-hosted, frickeldave-main]
    steps:
      - name: Print branch information
        run: |
          echo "Target branch: ${{ github.base_ref }}"
          echo "Source branch: ${{ github.head_ref }}"

      - name: Skip if not targeting 'main' or 'dev'
        if: github.base_ref != 'main' && github.base_ref != 'dev'
        run: |
          echo "â„¹ï¸  This workflow only applies to PRs targeting 'dev' and 'main' branch."
          echo "Current target: '${{ github.base_ref }}' - skipping checks."
          echo "âœ… This PR is not targeting 'dev' or 'main', so it passes."

      - name: Prevent any attempt to merge a branch other than 'dev' into 'main'.
        if: github.base_ref == 'main' && github.head_ref != 'dev'
        run: |
          echo "âŒ Merges into 'main' are only allowed from the 'dev' branch."
          echo "âŒ Your source branch is '${{ github.head_ref }}'."
          echo "âŒ Target branch is '${{ github.base_ref }}'."
          exit 1
          
      - name: Allow merge from dev->main or from any other branch->dev
        if:  (github.base_ref == 'main' && github.head_ref == 'dev') || (github.base_ref == 'dev')
        run: |
          echo "âœ… Merging into '${{ github.base_ref }}'. Start linting process..."

          # Install dependencies
          echo "â• Install dependencies"
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash
          echo 'export NODE_OPTIONS="--max-old-space-size=8192"' >> ~/.bashrc
          source ~/.bashrc
          nvm install --lts
          npm run ci || { echo "âŒ Installation of dependencies failed"; exit 1; }

          # Run ESLint check
          echo "ğŸ” Running ESLint check..."
          npm run lint:check || { echo "âŒ ESLint check failed"; exit 1; }
          
          # Run Prettier check
          echo "âœ¨ Running Prettier check..."
          npm run format:check || { echo "âŒ Prettier check failed"; exit 1; }
          
          # Run Vale prose check
          echo "ğŸ“ Running Vale prose check..."
          npm run prose || { echo "âŒ Vale prose check failed"; exit 1; }
          
          echo "âœ… All linting checks passed!"
